name: boilerplate_flutter_nafanesia
description: This is a boilerplate flutter by nafanesia.

# version build number
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # A flutter plugin for adapting screen and font size.
  # Guaranteed to look good on different models
  flutter_screenutil: ^1.1.0
  # lutter plugin for reading and writing simple key-value pairs.
  # Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^0.5.6+3
  # Approximate how your app looks and performs on another device.
  device_preview: ^0.3.0+1
  # A powerful Http client
  dio: ^3.0.9
  # Allows Flutter apps to discover network connectivity and configure themselves accordingly.
  # It can distinguish between cellular vs WiFi connection.
  connectivity: ^0.4.8+2
  # A mixture between dependency injection (DI) and state management,
  # built with widgets for widgets.
  provider: ^4.0.4
  # Simple direct Service Locator that allows to decouple the interface
  # from a concrete implementation and to access the concrete
  # implementation from everywhere in your App"
  get_it: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # add all assets images, icons, lang
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  # add font family, and next font asset
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_thin.ttf
          weight : 100
        - asset: assets/fonts/roboto_light.ttf
          weight: 300
        - asset: assets/fonts/roboto_reguler.ttf
        - asset: assets/fonts/roboto_medium.ttf
          weight : 500
        - asset: assets/fonts/roboto_bold.ttf
          weight : 700
